### ISSUE TITLE
Use the available space for the minute_buttons

### ISSUE THREAD

**Issue by mlangguth** [eyalgal/simple-timer-card#69]
Currently there are only 3 minute buttons in a row, even when there's enough space to display more (see screenshot). If would be great, if the available space would be used for the minute buttons and line breaks would only occure if needed.

<img width="602" height="452" alt="Image" src="https://github.com/user-attachments/assets/4fbfc6a2-63fa-4b95-b7fb-ee7aa3a570a3" />

**Comment by eyalgal** [comment]
Fixed in [v1.5.1](https://github.com/eyalgal/simple-timer-card/releases/tag/v1.5.1).

**Comment by mlangguth** [comment]
I updated to the new version. Unfortunately, it still looks exactly the same as before.
<img width="637" height="454" alt="Image" src="https://github.com/user-attachments/assets/85ca8ab7-538f-4b55-bc32-01dc021b7a38" />

**Comment by eyalgal** [comment]
Try clearing the cache. If you're using chrome, open the dashboard, press F12 (or right-click > Inspect) to open Developer Tools, then right-click and hold the refresh button, and select "Empty Cache and Hard Reload" from the menu that appears.

**Comment by mlangguth** [comment]
Still the same.

<img width="460" height="444" alt="Image" src="https://github.com/user-attachments/assets/a527356a-576f-4aa9-b3bf-7ac5e2416e3b" />
